service: compose-serverless-typescript

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:AWS_STAGE, opt:stage}
  region: ${env:AWS_REGION, opt:region}
  stackTags: # Optional CF stack tags
    Environment: ${env:AWS_STAGE, opt:stage}
    Product: "compose-serverless-typescript"
    Name: "compose-serverless-typescript-${env:AWS_STAGE, opt:stage}-serverless-cf"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-jest-plugin

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  hello:
    handler: src/handlers/health.healthCheck
    events:
      - http:
          path: health
          method: get